title: PhotonDB
description: Build high performance data stores in Rust.

url: "https://photondb.io"
github_username: photondb
twitter_username: photondb

# Build settings
theme: minima
plugins:
  - jekyll-feed

# For mathjax
markdown: kramdown
